spring.application.name=JavaTest

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=ecommerce
spring.datasource.password=123456

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in logs
spring.jpa.show-sql=true
